- id: conventional-commit-msg
  name: conventional-git commit message
  description: Validate Conventional Commits format on commit messages
  entry: conventional-git check commit --file
  language: system
  stages: [commit-msg]
  types: [text]
  require_serial: false
  pass_filenames: true

- id: conventional-branch-name
  name: conventional-git branch name
  description: Validate Conventional Branch format on branch names
  entry: conventional-git check branch
  language: system
  stages: [pre-commit, pre-push]
  always_run: true
  pass_filenames: false
